### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerInternal
  id: IConfigurationManagerInternal
  children:
  - System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  - System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  - System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  langs:
  - csharp
  name: IConfigurationManagerInternal
  nameWithType: IConfigurationManagerInternal
  fullName: System.Configuration.Internal.IConfigurationManagerInternal
  type: Interface
  summary: "Definieert een interface die wordt gebruikt door het .NET Framework voor het initialiseren van configuratie-eigenschappen."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerInternal
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  id: ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de configuratie-bestandsnaam die betrekking hebben op het pad van de toepassing."
  syntax:
    content: public string ApplicationConfigUri { get; }
    return:
      type: System.String
      description: "Een tekenreekswaarde die vertegenwoordigt de naam van een configuratiebestand."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  id: ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de lokale configuratiemap van de toepassing op basis van de invoer-assembly."
  syntax:
    content: public string ExeLocalConfigDirectory { get; }
    return:
      type: System.String
      description: "Een tekenreeks die de lokale configuratiemap vertegenwoordigt."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  id: ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u het pad van de lokale configuratie van de toepassing op basis van de invoer-assembly."
  syntax:
    content: public string ExeLocalConfigPath { get; }
    return:
      type: System.String
      description: "Een string-waarde die het pad van de lokale configuratie van de toepassing vertegenwoordigt."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  id: ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de naam van het product van de toepassing op basis van de invoer-assembly."
  syntax:
    content: public string ExeProductName { get; }
    return:
      type: System.String
      description: "Een tekenreekswaarde die vertegenwoordigt de naam van het product van de toepassing."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  id: ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de versie van het product van de toepassing op basis van de invoer-assembly."
  syntax:
    content: public string ExeProductVersion { get; }
    return:
      type: System.String
      description: "Een tekenreekswaarde voor de productversie van de toepassing."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  id: ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de zwervende configuratiemap van de toepassing op basis van de invoer-assembly."
  syntax:
    content: public string ExeRoamingConfigDirectory { get; }
    return:
      type: System.String
      description: "Een tekenreekswaarde voor de zwervende configuratiemap van de toepassing."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  id: ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Pad voor de configuratie van de zwervende gebruiker op basis van de toepassing vermelding assembly opgehaald."
  syntax:
    content: public string ExeRoamingConfigPath { get; }
    return:
      type: System.String
      description: "Een string-waarde die aangeeft pad voor de configuratie van de zwervende gebruiker."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  id: MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee wordt het pad voor de configuratie voor het Machine.config-bestand."
  syntax:
    content: public string MachineConfigPath { get; }
    return:
      type: System.String
      description: "Een string-waarde die het pad van het bestand Machine.config vertegenwoordigt."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  id: SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee wordt een waarde die het configuratiesysteem status aangeeft."
  remarks: "De eigenschap SetConfigurationSystemInProgress wordt gebruikt door <xref:System.Diagnostics>tijdens de initialisatie configuratie.</xref:System.Diagnostics>"
  syntax:
    content: public bool SetConfigurationSystemInProgress { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het configuratiesysteem wordt momenteel ge√Ønitialiseerd; anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Haalt een waarde die aangeeft of de gebruiker configuratie-instellingen worden ondersteund."
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Als het configuratiesysteem gebruiker configuratie-instellingen ondersteunt. anders <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  id: UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Hiermee haalt u de naam van het bestand dat wordt gebruikt voor het opslaan van de Gebruikersconfiguratie-instellingen."
  syntax:
    content: public string UserConfigFilename { get; }
    return:
      type: System.String
      description: "Een tekenreeks die de naam van het bestand dat wordt gebruikt voor het opslaan van de Gebruikersconfiguratie aangeeft."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
